### ISSUE TITLE
Missing services?

### ISSUE THREAD

**Issue by rillip3** [rackspace/rack#203]
I notice there's a lot of Rackspace API operations not covered; for example, cloud load balancer, monitoring, backups. I didn't see anything in the readme/docs/issues about any of those. Is there a roadmap for adding those? I don't want to burden everyone with tons of issues iff that's not appropriate.

**Comment by rillip3** [comment]
Also, contribution guidelines say to be sure to be familiar with the roadmap, but I don't see any link to the roadmap

**Comment by kenperkins** [comment]
We've enumerated a number of milestones with rough timelines; It's all dependent on feedback, but yes, we intend to support all of the services. I'll file an issue to update the roadmap.

**Comment by kenperkins** [comment]
We're tracking the roadmap in #206.

**Comment by jrperritt** [comment]
Closing this. The README has been updated with a roadmap.
