### ISSUE TITLE
Indicate sooner that `rack configure` is exactly what you want to get started

### ISSUE THREAD

**Issue by annegentle** [rackspace/rack#204]
I love this tool but would like to be clued in with `rack help` that I can get started with `rack configure` sooner than reading the docs. :) So, figure out if the user doesn't already have the profile set up, and then ask them if they'd like to go through it right away on install. 

I'd be happy to help with this with some assistance!

**Comment by kenperkins** [comment]
I'm not a fan of doing a check on every invocation of `rack` or `rack --help` to identify if a profile exists, and if not, jump into a configure session.

`rack` and `rack --help` already shows you in the list of commands that `configure` is an interactive session for setting up authentication. I'm not really sure what more we can do here.

**Comment by jrperritt** [comment]
I agree. If there was an install process, this would be possible, but currently there's nothing to be done here. @annegentle please reopen if we've missed something here.

**Comment by annegentle** [comment]
I wasn't thinking we'd check for configuration every time. How about:
 - move configure above init in the COMMANDS: section
 - add a DESCRIPTION: The rack CLI manages authentication, configures a local setup, and provides workflows for operations on Rackspace cloud resources.

Or, if we can't add a DESCRIPTION section, de-emphasize opinionated, that doesn't matter for getting work done in the cloud.

Seems like some string manipulation will work for what I was thinking of.
