### ISSUE TITLE
Make travis-ci deploy code use versioned paths

### ISSUE THREAD

**Issue by kenperkins** [rackspace/rack#227]
Also need to update to drgsites account.

**Comment by kenperkins** [comment]
put a `latest` link on DRC linking to a discreet path on akamai cdn.

i.e. `developer.rackspace.com/downloads/rack/osx/latest` > `akamai/version/1.0.0`

Need to update sphinx docs

**Comment by kenperkins** [comment]
Part of this was done in #235 by @rgbkrk

**Comment by rgbkrk** [comment]
* [X] Updated Sphinx docs for rackcli
* [X] Switch to drgsites account

**Comment by kenperkins** [comment]
We're going to continue to use master. This is complete.
