### ISSUE TITLE
Move to rackspace org

### ISSUE THREAD

**Issue by kenperkins** [rackspace/rack#245]
## Before move

- [x] Merge or reject current PRs

## The move

- [x] Transfer repository to github.com/rackspace (@jrperritt)
- [x] Update all code import statements to `rackspace/rack` (@rgbkrk)
- [x] Update the build/release/travis scripts to reference new remote (@rgbkrk)
- [x] Scrub all documentation for references (@rgbkrk)

## After move
- [x] Change repo URL for Read the Docs (@kenperkins, @jnoller)
- [x] Change the blurb text for customer email (@rgbkrk)
- [x] ~~Set up Travis configuration including secrets~~ (Apparently it's automatic with a proper transfer!)

**Comment by kenperkins** [comment]
This should be completed

**Comment by rgbkrk** [comment]
:boom:
