### ISSUE TITLE
Command `rack block-storage volume update` doesn't work with `--name` or `volume-id`.

### ISSUE THREAD

**Issue by DonNateR** [rackspace/rack#254]
Format of the command should as follows, `rack block-storage volume update --id <volumeID> [flags]`, however two complications occur. 

1) Even with the correct volume-id `--id` the request responds with an error. Here's an example:

`MPM1XEDV30:~ nath8916$ rack block-storage volume update --id 66dcbe53-1b62-4a15-adc2-e46e78b95f8b --description Response example` 
`error	Expected 0 args but got 1 Usage: rack block-storage volume update --id <volumeID> [flags]`

2) When entering the command without a directive after the flag, the help response comes up:

`MPM1XEDV30:~ nath8916$ rack block-storage volume update --id 66dcbe53-1b62-4a15-adc2-e46e78b95f8b --description`
`Incorrect Usage.`

`NAME: update - rack block-storage volume update --id <volumeID> [flags]`

`DESCRIPTION: Updates a volume`

`COMMAND FLAGS:`
`--id		[required] The ID of the volume to update.`
`--rename	[optional] A new name for this volume.`
`--description	[optional] A new description for this volume.`
`--fields	[optional] Only return these comma-separated case-insensitive fields.
		Choices: id, name, description, size, volumetype, snapshotid, attachments`

However, try a different flag and a different response occurs:

`MPM1XEDV30:~ nath8916$ rack block-storage volume update --id 66dcbe53-1b62-4a15-adc2-e46e78b95f8b --rename Response1`
`error	Missing flag: --volume-id is required.`

`--volume-id` isn't consistent with the standard `help` response. The required flag for volume id is `--id` in the help response, as opposed to `--volume-id` when the optional flag has changed to `rename`.

Either way, no combination I've attempted of `rack block-storage volume update` returns a successful response.

**Comment by jrperritt** [comment]
For the first one, you need quotation marks around any multi-word value in the shell. 

For the second one, `--description` takes a string value as its argument.

For the third one, that is indeed a bug :+1:
