### ISSUE TITLE
Incorrect help text for servers - image - get

### ISSUE THREAD

**Issue by rtgoodwin** [rackspace/rack#272]
Help text states:

`get		rack servers image get [--id <serverID> | --name <serverName> | --stdin id] [flags]`

The actual usage should be providing the image ID or image name. Also, the command in the nova/glance tools is "show", which more accurately reflects what is happening here. "Get" suggests that the image will be downloaded.

When an Images service is added, we'll need to make sure the terms align.

**Comment by jrperritt** [comment]
The help text is definitely a typo, so good find there.

The actions for the `images image` service will align with the `files object` service: `get` to retrieve information about the resource and `download` to download it.
