### ISSUE TITLE
versioning services in commands

### ISSUE THREAD

**Issue by jrperritt** [rackspace/rack#294]
When Rackspace decides to upgrade to a new version of a service, there will be a period of time when we will have to support 2 versions of a service. Below are some options to handle this:

1. Add a new `version` word in the 3rd position of the command: `rack servers v2 instance list`

2. Append the version to the service: `rack servers-v2 instance list`

3. Try to handle the command for the user with the currently-supported API  and fallback to the recently-deprecated API.

In my opinion, `1` is the cleanest but the most disruptive. It would require users to type and additional word in the command, while also having to know which version they want.

`2` would also require users to know which version they want, but would remove the extra word from the command.

`3` is the least disruptive, but the most taxing on the code base. Basically, it would amount to supporting all the possible sub-services (and flags per sub-service) for both versions of the service, and then trying to figure out based on the flags provided which one the user wants. In addition, having that logic in the codebase will be short-lived since after the grace period for supporting both versions is over, there'll be no need to keep it around. Though this option sounds like the best for users, it's really masking something they should be in control of.

Other attempts I can think of to solve this problem seem inconsistent. Namely:

1. Allowing for an optional version. As in, hypothetically, both `rack servers-v2 instance list` and `rack servers instance list` would work. Presumably the version-less command would point to the current service endpoint, but would change suddenly without warning over time.

Thoughts?

**Comment by carolynvs** [comment]
As a user, I don't know about the various API versions or care. When I'm in the Cloud Control panel, I don't see two sets of UIs when a new version has been rolled out. I use the same screen as before and while there may be some new options, I never have to remember implementation details, e.g. networking just moved from 2.0 to 2.1 so I need to pick which one I want to use. So 

As a developer, if a new version of the rackcli used the new version before I was ready to update my scripts, I'd just make sure that I kept using the last version of rackcli that worked. So maybe when backwards incompatible changes like new endpoint versions are released, we would bump our major release number to indicate that cleanly, a la [semver](http://semver.org).

**Comment by jrperritt** [comment]
That's a good idea. Then we'd only need to figure out the best way of communicating that the new release uses a new version of the service. Maybe a blog post and/or release notes are good enough.

Note though that we're exclusively talking about major version changes (2 -> 3 and not 2.1 -> 2.2). Changes to the minor could be added without issue. For the Cloud Control panel, many things are handled for the user behind the scenes. If they (or anyone else) were to offer 2 different major versions of a service, they'd handle it similar to `3` above.

**Comment by StephenBrown2** [comment]
:+1:  to Semver-bumping for API release changes. Holding back a utility because of backend changes is totally reasonable for end-users. Documentation in release notes should be emphasized, of course.

**Comment by jrperritt** [comment]
Closing this. I think aligning the implementation of a new version of a service with a new major version of `rack` is the way to go here. Thank you for your input @carolynvs and @StephenBrown2
