### ISSUE TITLE
unclear go error when not providing a region

### ISSUE THREAD

**Issue by jamiehannaford** [rackspace/rack#302]
If I do not provide a region in a command, I get back a blob of incomprehensible text:

> error Discovered 5 matching endpoints: []tokens.Endpoint{tokens.Endpoint{TenantID:"MossoCloudFS_UUID", PublicURL:"https://storage101.ord1.clouddrive.com/v1/MossoCloudFS_UUID", InternalURL:"https://snet-storage101.ord1.clouddrive.com/v1/MossoCloudFS_UUID", AdminURL:"", Region:"ORD", VersionID:"", VersionInfo:"", VersionList:""}, tokens.Endpoint{TenantID:"MossoCloudFS_UUID", PublicURL:"https://storage101.syd2.clouddrive.com/v1/MossoCloudFS_UUID", InternalURL:"https://snet-storage101.syd2.clouddrive.com/v1/MossoCloudFS_UUID", AdminURL:"", Region:"SYD", VersionID:"", VersionInfo:"", VersionList:""}, tokens.Endpoint{TenantID:"MossoCloudFS_UUID", PublicURL:"https://storage101.dfw1.clouddrive.com/v1/MossoCloudFS_UUID", InternalURL:"https://snet-storage101.dfw1.clouddrive.com/v1/MossoCloudFS_UUID", AdminURL:"", Region:"DFW", VersionID:"", VersionInfo:"", VersionList:""}, tokens.Endpoint{TenantID:"MossoCloudFS_UUID", PublicURL:"https://storage101.iad3.clouddrive.com/v1/MossoCloudFS_UUID", InternalURL:"https://snet-storage101.iad3.clouddrive.com/v1/MossoCloudFS_UUID", AdminURL:"", Region:"IAD", VersionID:"", VersionInfo:"", VersionList:""}, tokens.Endpoint{TenantID:"MossoCloudFS_UUID", PublicURL:"https://storage101.hkg1.clouddrive.com/v1/MossoCloudFS_UUID", InternalURL:"https://snet-storage101.hkg1.clouddrive.com/v1/MossoCloudFS_UUID", AdminURL:"", Region:"HKG", VersionID:"", VersionInfo:"", VersionList:""}}

it'd be better to have a more human-friendly error msg here

**Comment by indolering** [comment]
I had no idea what I had done wrong.
