### ISSUE TITLE
Expose URLs of a container in the `get` cmd

### ISSUE THREAD

**Issue by jamiehannaford** [rackspace/rack#306]
Can we expose the URLs (CDN, HTTPS, etc.) for a container? I want to know what the URL is after creating it. Right now we expose these fields during `rack files container get foo`:

> Name
> ObjectCount
> BytesUsed
> ContentLength
> AcceptRanges
> ContentType
> Read
> Write
> TransID
> VersionsLocation

**Comment by jrperritt** [comment]
Those are only relevant for CDN containers.

**Comment by jamiehannaford** [comment]
@jrperritt so should CDN-enabled containers be classed as a new subcommand, like this:

`rack files container create foo`
`rack files cdn-container get foo`

?

**Comment by jrperritt** [comment]
I'd say at least that. Technically, they should use a different service altogether since they have a different endpoint: `rack files-cdn container get foo`. I'd probably be alright integrating it with `files` though.

**Comment by StephenBrown2** [comment]
:+1:

**Comment by kenperkins** [comment]
Creating another service may be confusing considering we have both a cdn service (Rackspace CDN) and CDN enabled cloud files containers. I'm not sure how I feel about it being a separate service.

In pkgcloud, we blur this ambiguation (2 different endpoints) for the storage service, and just have cdn capabilities as part of storage operations.
