### ISSUE TITLE
Enabling/disabling CDN on a container?

### ISSUE THREAD

**Issue by jamiehannaford** [rackspace/rack#307]
I didn't see it anywhere, but do we allow users to enable and disable the CDN visibility for a container? If not, should they be separate commands, like:

`rack files container cdn-enable`
`rack files container cdn-disable`

**Comment by jrperritt** [comment]
CDN operations on containers aren't currently implemented. Because CDN operations use a different endpoint, If they were to be added, I think they'd be a separate subservice: 
`rack files cdn-container enable`.
