### ISSUE TITLE
Order of --profile is incorrect in https://developer.rackspace.com/docs/rack-cli/configuration/#config-file

### ISSUE THREAD

**Issue by annegentle** [rackspace/rack#308]
Reported on Twitter Here’s the URL - https://developer.rackspace.com/docs/rack-cli/configuration/#configuration — scroll down to just above Environment Variables.

**Comment by Valien** [comment]
You all rock. Thanks for logging this so quickly.

**Comment by jrperritt** [comment]
Fixed. Thank you for reporting this.
