### ISSUE TITLE
Create commands for the upcoming Rackspace Container Service

### ISSUE THREAD

**Issue by rgbkrk** [rackspace/rack#327]
We're going to want to target the container service. For the moment we'll be using the proxy API from @thomasem + team. Eventually we'll be using the Magnum API once exposed (which we'll support in Gophercloud proper).

In the meantime, we should layout what the CLI commands will be.

/cc @kenperkins @jrperritt

**Comment by jrperritt** [comment]
this has its own tool, i think. closing
