### ISSUE TITLE
README is missing rationale for project's existence

### ISSUE THREAD

**Issue by jasondunsmore** [rackspace/rack#354]
It's customary in the open source world for a project, which is the successor of another project, to lay out a rationale for the transition to the new project.  This is to put users and developers minds at ease, since transitioning libraries often requires a non-trivial amount of effort.  Users will naturally think: "is this project going to stick around, or will I be doing this work again in a year?"  Here are a few questions that came to mind when I heard about this project:

Why not fix Pyrax? https://github.com/rackspace/pyrax

Why not use python so that code from upstream projects can be reused?  This would greatly reduce the overall maintenance burden.  For example, every time a new feature is added to an OpenStack project, support will have to be added in the upstream client AND in this client.

In the above scenario, how quickly will support be added to this client?  Support for new features in upstream clients is usually added at the same time or just after the feature lands.

Why was Pyrax abandoned, and is this project likely to be abandoned for the same reason?

**Comment by jnoller** [comment]
Hi Jason!

I agree we should add some more details in the readme, but I have some points / corrections below:
> It's customary in the open source world for a project, which is the successor of another project, to lay out a rationale for the transition to the new project.
> 
Please note that 'rack' is not a successor to another project. The goal is to create a customer / user first command line interface. This means simple configuration, single binary (zero install) and clean and straightforward commands to maximize the user experience.

> This is to put users and developers minds at ease, since transitioning libraries often requires a non-trivial amount of effort. Users will naturally think: "is this project going to stick around, or will I be doing this work again in a year?"
> 
As 'rack' was built specifically for customers, is open source and officially supported it will be around for some time. It is also built on:

https://github.com/rackspace/gophercloud

Which is another OSS go based SDK with openstack first design in mind, following the lead of other pure SDKs such as openstack.net, jclouds, python-openstacksdk and others.

'Rack' is a thin CLI for command line use only and not to be imported into code. You would use gophercloud for that in a go project.
> Here are a few questions that came to mind when I heard about this project:
> 
> Why not fix Pyrax? https://github.com/rackspace/pyrax
> 
Pyrax is broken on a fundamental level and is being replaced by:

https://wiki.openstack.org/wiki/SDK-Development/PythonOpenStackSDK

Which is a pure openstack python sdk in upstream. Rack does not replace Pyrax.
> Why not use python so that code from upstream projects can be reused? This would greatly reduce the overall maintenance burden. For example, every time a new feature is added to an OpenStack project, support will have to be added in the upstream client AND in this client.
> 
That is correct; however we invested quite a bit of time and effort into making the same user experience, single binary zero install in python in upstream, ourselves, and elsewhere and as a 13 year Python veteran even I had to admit the build tools for simple CLIs that didn't make for a bad user experience simply aren't there.

For example, in the case you outlined - frequently the Python-*clients if not carefully put into isolated virtualenvs on every OS will clobber each other's dependencies/versions. This doesn't even touch on the issues for a simple Windows build/install.
> In the above scenario, how quickly will support be added to this client? Support for new features in upstream clients is usually added at the same time or just after the feature lands.
> 
Agreed; there will be lag time unless we gain more feature contributors to gophercloud, we are in the process of moving gophercloud into its own org / etc to help accelerate it as it really is a go based sdk for openstack.
> Why was Pyrax abandoned, and is this project likely to be abandoned for the same reason?
> 
I believe I address this above - rack is not an SDK. The closest equivalent would be python-openstackclient which suffers the same usability and installation issues the other clients suffer from.

The real replacement for Pyrax as I mentioned is https://wiki.openstack.org/wiki/SDK-Development/PythonOpenStackSDK

That will eventually become the back end for most of the upstream clients and by then python's tooling / deployment for consumer tools may be at a point where rack could be swapped to Python.

Jesse

**Comment by jasondunsmore** [comment]
Thanks for the info Jesse.  Am I correct in assuming that https://github.com/rackerlabs/rackspace-sdk-plugin/ is the successor to pyrax?  Will it provide support for all of the Rackspace cloud resources that aren't 100% compatible with OpenStack like pyrax did?  If so, is there an approximate timeframe for reaching that goal?  The reason I ask is because we, on the Heat product team, are having to maintain a fork of pyrax https://github.com/rackerlabs/heat-pyrax/commits/temp-patch-deploy since the project has been abandoned and there is no viable alternative.

**Comment by jnoller** [comment]
Yes, that's correct - full support. @kenperkins can help with timeframes

**Comment by jrperritt** [comment]
I think the README adequately addresses the rationale for this project's existence. Questions about the Rackspace plugin for the OpenStack SDK can be posted to that repo.
