### ISSUE TITLE
Add file filtering to upload-dir?

### ISSUE THREAD

**Issue by jamiehannaford** [rackspace/rack#356]
Would it be a good idea to add a new flag to `upload-dir` to allow file filtering by pattern? For example:

```bash
rack files object upload-dir --name foo --dir . --regex-filter "^wp_.*\.php$"
```

I know you can pipe in stdout from `find` or whatever, but you don't get the concurrency of `upload-dir`. I can implement this

**Comment by jrperritt** [comment]
Couldn't you just use `mv` with a regex?
```
mkdir tmp && mv "^wp_.*\.php$" tmp && rack files object upload-dir --name foo --dir tmp
```

**Comment by jamiehannaford** [comment]
Yeah, I didn't think of that. Good solution
