### ISSUE TITLE
Edits for CLI docs

### ISSUE THREAD

**Issue by kmsholcomb** [rackspace/rack#377]
I copy-edited the Rackspace CLI documentation that is visible at https://developer.rackspace.com/docs/rack-cli/. The markup is in the attached Word docs. (I tried to upload a zip file, but GitHub wouldn't let me!) Please contact me if you have any questions. Thanks!

[rack CLI_ configuration_editsKH.docx](https://github.com/rackspace/rack/files/64501/rack.CLI_.configuration_editsKH.docx)
[rack CLI_examples_block-storage_editsKH.docx](https://github.com/rackspace/rack/files/64502/rack.CLI_examples_block-storage_editsKH.docx)
[rack CLI_examples_files_editsKH.docx](https://github.com/rackspace/rack/files/64504/rack.CLI_examples_files_editsKH.docx)
[rack CLI_examples_index_editsKH.docx](https://github.com/rackspace/rack/files/64503/rack.CLI_examples_index_editsKH.docx)
[rack CLI_examples_networks_editsKH.docx](https://github.com/rackspace/rack/files/64506/rack.CLI_examples_networks_editsKH.docx)
[rack CLI_examples_orchestration_editsKH.docx](https://github.com/rackspace/rack/files/64505/rack.CLI_examples_orchestration_editsKH.docx)
[rack CLI_examples_servers_editsKH.docx](https://github.com/rackspace/rack/files/64507/rack.CLI_examples_servers_editsKH.docx)
[rack CLI_global options_editsKH.docx](https://github.com/rackspace/rack/files/64511/rack.CLI_global.options_editsKH.docx)
[rack CLI_index_editsKH.docx](https://github.com/rackspace/rack/files/64512/rack.CLI_index_editsKH.docx)
[rack CLI_services_block-storage_editsKH.docx](https://github.com/rackspace/rack/files/64509/rack.CLI_services_block-storage_editsKH.docx)
[rack CLI_services_files_editsKH.docx](https://github.com/rackspace/rack/files/64510/rack.CLI_services_files_editsKH.docx)
[rack CLI_services_index_editsKH.docx](https://github.com/rackspace/rack/files/64508/rack.CLI_services_index_editsKH.docx)
[rack CLI_services_networks_editsKH.docx](https://github.com/rackspace/rack/files/64513/rack.CLI_services_networks_editsKH.docx)
[rack CLI_services_orchestration_editsKH.docx](https://github.com/rackspace/rack/files/64516/rack.CLI_services_orchestration_editsKH.docx)
[rack CLI_services_servers_editsKH.docx](https://github.com/rackspace/rack/files/64515/rack.CLI_services_servers_editsKH.docx)
[rack CLI_troubleshooting a request_editsKH.docx](https://github.com/rackspace/rack/files/64514/rack.CLI_troubleshooting.a.request_editsKH.docx)

**Comment by jrperritt** [comment]
@kmsholcomb Thank you for the edits. Can you submit them in a pull request?

**Comment by kmsholcomb** [comment]
@jrperritt Sure, but it will take me while. I can probably get to it this week.

**Comment by jrperritt** [comment]
Thank you. We're not in any hurry  :)

**Comment by kmsholcomb** [comment]
I've started creating PRs for the docs files. I'm going to create one per doc file. Merge them as you see fit.

**Comment by kmsholcomb** [comment]
I've created 16 PRs in the repo, one for each docs file. If you find issues, please fix them or let me know and I will fix them. Thanks!

**Comment by jrperritt** [comment]
closing since these were broken out into individual prs. thanks @kmsholcomb
