### ISSUE TITLE
Rebuild fails for servers which could use manual disk configuration

### ISSUE THREAD

**Issue by carolynvs** [rackspace/rack#379]
1. Create a server which could use manual disk configuration
    * Ubuntu 14.04 LTS (Trusty Tahr) (PV)
    * 1GB Standard Instance
2. Attempt to rebuild the server using the rack cli.

`error	DiskConfig must be either diskconfig.Auto or diskconfig.Manual.`

```bash
$ rack servers instance create --name bugtest --flavor-id 3 --image-id 5ed162cc-b4eb-4371-b24a-a0ae73376c73 --wait-for-completion

$ rack servers instance rebuild --name bugtest --image-id 5ed162cc-b4eb-4371-b24a-a0ae73376c73 --admin-pass *** --wait-for-completion
error	DiskConfig must be either diskconfig.Auto or diskconfig.Manual.
```

It appears that the API expects `OS-DCF:diskConfig` to be specified during a rebuild of an instance which could use manual disk config? I get this error for instances with both manual and automatic disk configuration.

Is there a way to pass custom json data to the API request? Or perhaps a new optional flag is needed for disk config?

**Comment by rgbkrk** [comment]
Sure seems like it. Thanks for reporting this one.

**Comment by sigmavirus24** [comment]
I'm running into this with the version presently uploaded to https://developer.rackspace.com/docs/rack-cli/. Is there a way to work around this until a new binary with #380 is released?

**Comment by jrperritt** [comment]
You can [build from source](https://github.com/rackspace/rack#build-from-source).

I'll try to get v1.2 pushed out this week.
