### ISSUE TITLE
Statically link the rack binary

### ISSUE THREAD

**Issue by everett-toews** [rackspace/rack#381]
To make `rack` as independent/portable as possible, the binary should be statically linked on build.

I discovered this while attempting to get `rack` to run on Alpine Linux in [Installed Go binary not found in path on Alpine Linux Docker](http://stackoverflow.com/questions/34729748/installed-go-binary-not-found-in-path-on-alpine-linux-docker).

There are a number of good posts on this out there at [Building Minimal Docker Containers for Go Applications](https://blog.codeship.com/building-minimal-docker-containers-for-go-applications/), [Building Docker Images for Static Go Binaries](https://medium.com/@kelseyhightower/optimizing-docker-images-for-static-binaries-b5696e26eb07#.5jooriq7p), etc.

**Comment by elwinar** [comment]
I stumbled upon the SO thread, and just want to add an alternative solution for packages that use CGO bindings (like the SQLite one) : https://www.elwinar.com/articles/statically-link-golang-binaries
