### ISSUE TITLE
Make switching profiles easier

### ISSUE THREAD

**Issue by eljrax** [rackspace/rack#386]
Requiring having the --profile option (or any other for that matter) at the end of a string is quite inconvenient.

It's rare that you'll only fire off a single command, most of what we do are series of commands (find image ID, flavor ID, build instance, show instance ...) Constantly having to ctrl+left arrow twice in order to switch subcommand/action is a massive inconvenience.
I've aliased my way out of this for now, but positional arguments feels a bit uncalled for here. 

Ideally --profile (or any other globally applicable options) should come right after the rack command. Or if that's not doable for whatever reason, at least allow for something along the lines of
`rack profile activate <profilename>`
and apply the selected profile to all future commands until switched.

**Comment by Trozz** [comment]
having the ability to activate a profile would be the ideal situation as ultimately it is as simple as adding an enabled flag to the config file to determine which profile is currently active and use the --profile option to ignore this

**Comment by jrperritt** [comment]
@eljrax @Trozz thoughts on user experience here: https://github.com/rackspace/rack/pull/432#issuecomment-217520408 ?

**Comment by Trozz** [comment]
@jrperritt that looks great, i think that solves this issue

**Comment by eljrax** [comment]
@jrperritt I don't have a strong preference or thoughts on the "show active region" debate in #432, so whatever the outcome of that, this looks good to me! Thanks!

**Comment by jrperritt** [comment]
by #432

**Comment by eljrax** [comment]
Looks good, thanks!
