### ISSUE TITLE
Rebuild command needs to exclude name from request

### ISSUE THREAD

**Issue by sigmavirus24** [rackspace/rack#387]
I'm using the HEAD of master (presently 7e0867ce8ed27549bf4ccf22822a277540fa4886) and trying to run

```
$ rack servers instance rebuild --id <server-id> --admin-pass t3stpa55word --image-id 09de0a66-3156-48b4-90a5-1cf25a905207 --log debug
```

But the client is receiving a 400. I noticed in the debug output that the request body looks like:

```json
{
  "rebuild": {
    "adminPass": "t3stpa55word",
    "imageRef": "09de0a66-3156-48b4-90a5-1cf25a905207",
    "name": ""
  }
}
```

Which I suspect is why the compute API is returning a `400 Bad Request`

If I provide `--name <name-of-server>` instead of `--id <server-id>` then the request succeeds.

---

```
$ rack version
rack version 1.1.0-beta1-15-g7e0867c
commit: 7e0867ce8ed27549bf4ccf22822a277540fa4886
```

**Comment by sigmavirus24** [comment]
I suspect the fix needs to be somewhere around [here](https://github.com/rackspace/rack/blob/fc8ffcc3b66238063be59f39068401ac78185ee5/internal/github.com/rackspace/gophercloud/openstack/compute/v2/extensions/diskconfig/requests.go#L99) but I'm not familiar enough with the library/language conventions to make the patch myself.

**Comment by jrperritt** [comment]
Ah, thank you. Yes, I see `name` is added to the request body even when it isn't provided. Try the `HEAD` of `master` now. I've just pushed [what I think is] a fix.

**Comment by sigmavirus24** [comment]
I'll pull and test this out. Thanks @jrperritt

**Comment by sigmavirus24** [comment]
Confirmed it works. :+1:
