### ISSUE TITLE
Static links to latest binaries

### ISSUE THREAD

**Issue by zack-shoylev** [rackspace/rack#389]
Please make static links available for the latest binaries, instead of the current links (current links are in this form: https://ec4a542dbf90c03b9f75-b342aba65414ad802720b41e8159cf45.ssl.cf5.rackcdn.com/1.1.0-beta1/Linux/amd64/rack)

This is needed to make it easier to develop and update docker images, for example.

**Comment by carolynvs** [comment]
While we may not want to just use the existing infrastructure of download.getcarina.com that we are using to provide this exact feature for `carina` and `dvm` (since rack isn't really for Carina), maybe we can rip off their cloud files deploy script.

**Comment by everett-toews** [comment]
Conceivably, if we had something like https://download.developer.rackspace.com/latest/Linux/amd64/rack we wouldn't have to worry about updating images at all. We could create an automated build for `rack` at https://hub.docker.com/u/rackspace/rack/ and the `rackspace/rack:latest` would always truly be the latest based on the `master` branch. 

If users wanted specific point in time versions like `rackspace/rack:1.2.0`, we could do that but I'm not even sure that's necessary for a CLI like this.
