### ISSUE TITLE
Is it possible to set headers on cloud files object? (X-Delete-After)

### ISSUE THREAD

**Issue by melon-babak** [rackspace/rack#392]
It seems like it is possible to set `metadata` but not headers at the moment?

I want to upload a file to cloud files with an expiry.

Thanks for any guidance.

```
rack version 1.1.0-beta1
commit: 7e73c5fa6e420edf901cf7ca217ffeaed8744b1a
```

**Comment by jrperritt** [comment]
Thank you for pointing this out. You're correct that the `X-Delete-After` header currently isn't an option in `rack`. I will add it next week and publish a minor release.

**Comment by TylerODonnell** [comment]
Hey @jrperritt.

We're interested in using this for our rolling backup solution. Do you have any estimate when this feature will be published?

Thanks!

**Comment by jrperritt** [comment]
@TylerODonnell @melon-babak Sorry guys, I meant to update this ticket. If y'all don't mind [building the CLI yourselves](https://github.com/rackspace/rack#build-from-source), I'll have something in `master` before this time tomorrow. For the minor release, it was decided that we'd wait  to push a minor release until something bigger was ready. As it happens, the PR for Cloud Databases support is being reviewed as we speak, so I suspect it'll be ready by the end of this week.

**Comment by TylerODonnell** [comment]
Awesome to hear! Thanks for the update @jrperritt

**Comment by jrperritt** [comment]
Ok, the `delete-at` and `delete-after` flags are available in `master` if y'all want to build and try it out.

**Comment by TylerODonnell** [comment]
Thanks for being so quick! I'll give it a try this evening. Thanks a lot @jrperritt.

**Comment by jrperritt** [comment]
Thank y'all for your patience. Please follow up with any issues, regarding this or otherwise.
