### ISSUE TITLE
Support create image in servers interface

### ISSUE THREAD

**Issue by kenperkins** [rackspace/rack#393]
```
rack servers image create --server-id 12345678-abcd-abcd-abcd-1234567890ab --name my-golden-image
```
https://developer.rackspace.com/docs/cloud-servers/v2/developer-guide/#create-image-of-specified-server

Part of the motivation is to start moving how-to documents to use `rack` in lieu of `supernova`

**Comment by jrperritt** [comment]
I think we can get this in for 1.2, which I'd like to feature-freeze at the end of this Tuesday.

**Comment by jrperritt** [comment]
by #434
