### ISSUE TITLE
Can not get a public ip when specifying a private network

### ISSUE THREAD

**Issue by devx** [rackspace/rack#394]
This might be a documentation issue however when ever I create a server and give it a private network it  is created with out a public network which is what I expect.

```
 rack servers instance create --name test-server  --image-name "CoreOS (Beta)" --flavor-name "8 GB Performance" --networks "b7e08db1-a379-47e4-b9d9-14290e00b1ea" 
```

However I would like to give it private network and for it to still have a public ip. I apologize if this has been covered somewhere, as I was not able to find it.

**Comment by jrperritt** [comment]
That's a great question and not one I think we cover in the documentation, though we should. You should be able to pass the fixed public network ID along with your private network ID:

` rack servers instance create --name test-server  --image-name "CoreOS (Beta)" --flavor-name "8 GB Performance" --networks "b7e08db1-a379-47e4-b9d9-14290e00b1ea,00000000-0000-0000-0000-000000000000"`

**Comment by jrperritt** [comment]
@devx Were you able to get that to work?

**Comment by devx** [comment]
Sorry for the delayed response, and yes adding the "00000000-0000-0000-0000-000000000000" network gave it a public ip, but no service net ID.
