### ISSUE TITLE
fatal error: runtime: out of memory during download

### ISSUE THREAD

**Issue by epicavic** [rackspace/rack#441]
hello guys,

i've been trying to download file 2.9 g in size from rackspace cloud
and rack client has crashed with oom exception
i've tried once again - same result, checked memory consumption while client was working - it has consumed more than 3 g of res memory and kept growing
here is a traceback after client failure

`/usr/local/bin/rack files object download --container ${cname} --name ${fname} > ${fname}
fatal error: runtime: out of memory
runtime stack:
runtime.SysMap(0xc408300000, 0xbddc0000, 0x0, 0xcd9698)
	/home/travis/.gimme/versions/go1.4.linux.amd64/src/runtime/mem_linux.c:149 +0x98
runtime.MHeap_SysAlloc(0xcded80, 0xbddc0000, 0x435982)
	/home/travis/.gimme/versions/go1.4.linux.amd64/src/runtime/malloc.c:284 +0x124
runtime.MHeap_Alloc(0xcded80, 0x5eeda, 0x100000000, 0xcce570)
	/home/travis/.gimme/versions/go1.4.linux.amd64/src/runtime/mheap.c:240 +0x66

goroutine 15 [running]:
runtime.switchtoM()
	/home/travis/.gimme/versions/go1.4.linux.amd64/src/runtime/asm_amd64.s:198 fp=0xc2081bcdf8 sp=0xc2081bcdf0
runtime.mallocgc(0xbddb3800, 0x0, 0xa8007f2a00000003, 0xc20834f640)
	/home/travis/.gimme/versions/go1.4.linux.amd64/src/runtime/malloc.go:199 +0x9f3 fp=0xc2081bcea8 sp=0xc2081bcdf8
runtime.rawstring(0xbddb3800, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.4.linux.amd64/src/runtime/string.go:195 +0x93 fp=0xc2081bced8 sp=0xc2081bcea8
runtime.slicebytetostring(0xc3082d0000, 0xbddb3800, 0xfffffe00, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.4.linux.amd64/src/runtime/string.go:69 +0x4b fp=0xc2081bcf68 sp=0xc2081bced8
github.com/rackspace/rack/auth.(*LogRoundTripper).logResponseBody(0xc20801f160, 0x7f2ac25fb048, 0xc20834f640, 0xc2083656b0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/rackspace/rack/auth/clients.go:420 +0x643 fp=0xc2081bd120 sp=0xc2081bcf68
github.com/rackspace/rack/auth.(*LogRoundTripper).RoundTrip(0xc20801f160, 0xc208318680, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/rackspace/rack/auth/clients.go:369 +0x8b7 fp=0xc2081bd348 sp=0xc2081bd120
net/http.send(0xc208318680, 0x7f2ac25f3860, 0xc20801f160, 0x9a, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.4.linux.amd64/src/net/http/client.go:219 +0x4fc fp=0xc2081bd438 sp=0xc2081bd348
net/http.(*Client).send(0xc20803aff8, 0xc208318680, 0x9a, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.4.linux.amd64/src/net/http/client.go:142 +0x15b fp=0xc2081bd508 sp=0xc2081bd438
net/http.(*Client).doFollowingRedirects(0xc20803aff8, 0xc208318680, 0xad5e50, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.4.linux.amd64/src/net/http/client.go:367 +0xb25 fp=0xc2081bd708 sp=0xc2081bd508
net/http.(*Client).Do(0xc20803aff8, 0xc208318680, 0xc, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.4.linux.amd64/src/net/http/client.go:174 +0xa4 fp=0xc2081bd750 sp=0xc2081bd708
github.com/rackspace/rack/internal/github.com/rackspace/gophercloud.(*ProviderClient).Request(0xc20803afc0, 0x9b5f70, 0x3, 0xc20834b360, 0x9a, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/rackspace/rack/internal/github.com/rackspace/gophercloud/provider_client.go:165 +0x655 fp=0xc2081bdb50 sp=0xc2081bd750
github.com/rackspace/rack/internal/github.com/rackspace/gophercloud/openstack/objectstorage/v1/objects.Download(0xc2080b2840, 0xc208033318, 0x6, 0xc20834f500, 0x37, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/rackspace/rack/internal/github.com/rackspace/gophercloud/openstack/objectstorage/v1/objects/requests.go:142 +0x3e1 fp=0xc2081bdd90 sp=0xc2081bdb50
github.com/rackspace/rack/internal/github.com/rackspace/gophercloud/rackspace/objectstorage/v1/objects.Download(0xc2080b2840, 0xc208033318, 0x6, 0xc20834f500, 0x37, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/rackspace/rack/internal/github.com/rackspace/gophercloud/rackspace/objectstorage/v1/objects/delegate.go:32 +0x90 fp=0xc2081bde40 sp=0xc2081bdd90
github.com/rackspace/rack/commands/filescommands/objectcommands.(*commandDownload).Execute(0xc208040028, 0xc20836b590)
	/home/travis/gopath/src/github.com/rackspace/rack/commands/filescommands/objectcommands/download.go:91 +0x11a fp=0xc2081bdf48 sp=0xc2081bde40
github.com/rackspace/rack/handler.func·004(0xcd6100, 0x0, 0x0, 0x7faa40, 0xc20836fb60, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/rackspace/rack/handler/handle.go:185 +0x7b fp=0xc2081bdf98 sp=0xc2081bdf48
runtime.goexit()
	/home/travis/.gimme/versions/go1.4.linux.amd64/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc2081bdfa0 sp=0xc2081bdf98
created by github.com/rackspace/rack/handler.handleExecute
	/home/travis/gopath/src/github.com/rackspace/rack/handler/handle.go:188 +0xcf8

goroutine 1 [chan receive, 1 minutes]:
github.com/rackspace/rack/handler.Handle(0x7f2ac25f3708, 0xc208040028)
	/home/travis/gopath/src/github.com/rackspace/rack/handler/handle.go:112 +0x4cc
github.com/rackspace/rack/commands/filescommands/objectcommands.actionDownload(0xc20800ad20)
	/home/travis/gopath/src/github.com/rackspace/rack/commands/filescommands/objectcommands/download.go:53 +0xd4
github.com/rackspace/rack/internal/github.com/codegangsta/cli.Command.Run(0x9d9e30, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc208036120, 0x52, 0x9f37b0, ...)
	/home/travis/gopath/src/github.com/rackspace/rack/internal/github.com/codegangsta/cli/command.go:118 +0x1044
github.com/rackspace/rack/internal/github.com/codegangsta/cli.(*App).RunAsSubcommand(0xc20806be00, 0xc20800ab60, 0x0, 0x0)
	/home/travis/gopath/src/github.com/rackspace/rack/internal/github.com/codegangsta/cli/app.go:257 +0xc2a
github.com/rackspace/rack/internal/github.com/codegangsta/cli.Command.startApp(0x9c1f70, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0xa3d4f0, 0x25, 0x0, ...)
	/home/travis/gopath/src/github.com/rackspace/rack/internal/github.com/codegangsta/cli/command.go:183 +0x505
github.com/rackspace/rack/internal/github.com/codegangsta/cli.Command.Run(0x9c1f70, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0xa3d4f0, 0x25, 0x0, ...)
	/home/travis/gopath/src/github.com/rackspace/rack/internal/github.com/codegangsta/cli/command.go:45 +0x14ee
github.com/rackspace/rack/internal/github.com/codegangsta/cli.(*App).RunAsSubcommand(0xc20806bd00, 0xc20800aa80, 0x0, 0x0)
	/home/travis/gopath/src/github.com/rackspace/rack/internal/github.com/codegangsta/cli/app.go:257 +0xc2a
github.com/rackspace/rack/internal/github.com/codegangsta/cli.Command.startApp(0x9be8d0, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0xa3ddb0, 0x22, 0x0, ...)
	/home/travis/gopath/src/github.com/rackspace/rack/internal/github.com/codegangsta/cli/command.go:183 +0x505
github.com/rackspace/rack/internal/github.com/codegangsta/cli.Command.Run(0x9be8d0, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0xa3ddb0, 0x22, 0x0, ...)
	/home/travis/gopath/src/github.com/rackspace/rack/internal/github.com/codegangsta/cli/command.go:45 +0x14ee
github.com/rackspace/rack/internal/github.com/codegangsta/cli.(*App).Run(0xc20806bc00, 0xc20800a000, 0xe, 0xe, 0x0, 0x0)
	/home/travis/gopath/src/github.com/rackspace/rack/internal/github.com/codegangsta/cli/app.go:160 +0xd0c
main.main()
	/home/travis/gopath/src/github.com/rackspace/rack/main.go:36 +0x3b7

goroutine 12 [runnable]:
net/http.(*persistConn).readLoop(0xc20806cfd0)
	/home/travis/.gimme/versions/go1.4.linux.amd64/src/net/http/transport.go:928 +0x9ce
created by net/http.(*Transport).dialConn
	/home/travis/.gimme/versions/go1.4.linux.amd64/src/net/http/transport.go:660 +0xc9f

goroutine 13 [select, 1 minutes]:
net/http.(*persistConn).writeLoop(0xc20806cfd0)
	/home/travis/.gimme/versions/go1.4.linux.amd64/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/home/travis/.gimme/versions/go1.4.linux.amd64/src/net/http/transport.go:661 +0xcbc

goroutine 10 [select, 1 minutes]:
net.func·019()
	/home/travis/.gimme/versions/go1.4.linux.amd64/src/net/dnsclient_unix.go:241 +0x2f4
created by net.loadConfig
	/home/travis/.gimme/versions/go1.4.linux.amd64/src/net/dnsclient_unix.go:269 +0x20c`

**Comment by jrperritt** [comment]
What's the output of `/usr/local/bin/rack version`?

**Comment by epicavic** [comment]
# /usr/local/bin/rack version
rack version 1.2
commit: 09c14b061f4a115c8f1ff07ae6be96d9b11e08df

**Comment by jrperritt** [comment]
I'm looking into it.

**Comment by jrperritt** [comment]
`rack files object download` will load the entire response in memory before completing; that's just how the OpenStack/Rackspace API has been designed for downloading a regular object.

If, however, you use the large-object API (via `rack files large-object upload`), the object will be segmented into pieces, uploaded, and then, when downloaded, memory usage (on the part of the object) should only be the size of a single segment. You can see the flags for the command by running `rack files large-object upload --help`. Docs for it are [here](https://developer.rackspace.com/docs/rack-cli/services/files/#large-object) (note that after `upload` and `delete` are the only actions that need to be taken on a large object. `download` is done by the regular `rack files object download` command).

**Comment by epicavic** [comment]
well...you definitely have to redesign download/upload tool logic :)
i suppose that it's not quite right when tool eats amount of memory equal to downloaded file size.
memory footprint should be as small as possible, especially if tool is used for downloading/uploading of big files on small sized vm's.

i hope that you will fix memory issue in the future.

**Comment by pitaylor** [comment]
I'm getting the same out of memory error when downloading a ~3gb file that was uploaded with `large-object upload` and that has been split into 200mb segments. I don't believe that the memory usage is constrained to the size of a single segment. Memory usage of the `rack` process grows to several gigabytes before erroring out.

Can this ticket be re-opened? I agree with epicavic that ideally it would work regardless of segment size.

**Comment by Nowaker** [comment]
A suggestion to use `large-object upload` when there's a problem with `object download` doesn't make sense. Loading the whole file into memory doesn't make sense either.
